apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: classifier
  name: projectsveltos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: projectsveltos
  labels:
    control-plane: classifier
spec:
  selector:
    matchLabels:
      control-plane: classifier
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: classifier
    spec:
      securityContext:
        runAsNonRoot: true
        # TODO(user): For common cases that do not require escalating privileges
        # it is recommended to ensure that all your Pods/Containers are restrictive.
        # More info: https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted
        # Please uncomment the following code if your project does NOT have to work on old Kubernetes
        # versions < 1.19 or on vendors versions which do NOT support this field by default (i.e. Openshift < 4.11 ).
        # seccompProfile:
        #   type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        - --report-mode=1
        - --v=5
        image: controller:latest
        imagePullPolicy: Always
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        # TODO(user): Configure the resources accordingly based on the project requirements.
        # More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 500m
            memory: 128Mi
      serviceAccountName: classifier-manager
      terminationGracePeriodSeconds: 10
---
# This default Classifier is needed so any cluster
# where sveltos-agent is installed is labeled
apiVersion: lib.projectsveltos.io/v1alpha1
kind: Classifier
metadata:
  name: default-classifier
spec:
  classifierLabels:
   - key: sveltos-agent
     value: present