# permissions for end users to view classifiers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: classifier-viewer-role
rules:
- apiGroups:
  - classify.projectsveltos.io
  resources:
  - classifiers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - classify.projectsveltos.io
  resources:
  - classifiers/status
  verbs:
  - get
