# permissions for end users to edit classifiers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: classifier-editor-role
rules:
- apiGroups:
  - classify.projectsveltos.io
  resources:
  - classifiers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - classify.projectsveltos.io
  resources:
  - classifiers/status
  verbs:
  - get
