# permissions for end users to edit classifierreports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: classifierreport-editor-role
rules:
- apiGroups:
  - classify.projectsveltos.io
  resources:
  - classifierreports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - classify.projectsveltos.io
  resources:
  - classifierreports/status
  verbs:
  - get
