# permissions for end users to view classifierreports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: classifierreport-viewer-role
rules:
- apiGroups:
  - classify.projectsveltos.io
  resources:
  - classifierreports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - classify.projectsveltos.io
  resources:
  - classifierreports/status
  verbs:
  - get
