# Following Classifier uses Lua script.
# Any cluster with at least one ClusterIssuer containinghe
# acme-staging-v02.api.letsencrypt.org in the server field, will be a match
apiVersion: lib.projectsveltos.io/v1beta1
kind: Classifier
metadata:
  name: acme-staging-v02
spec:
  classifierLabels:
  - key: issuer
    value: acme-staging-v02
  deployedResourceConstraint:
  - group: "cert-manager.io"
    version: v1
    kind: ClusterIssuer
    minCount: 1
    script: |
      function evaluate()
        hs = {}
        hs.matching = false
        hs.message = ""
        if obj.spec.acme ~= nil then
          if string.find(obj.spec.acme.email, "acme-staging-v02.api.letsencrypt.org", 1, true) then
            hs.matching = true
          end
        end
        return hs
      end
